CREATE TABLE `car_images` (
	`id` text PRIMARY KEY NOT NULL,
	`car_id` text NOT NULL,
	`path` text NOT NULL,
	`sort_order` integer NOT NULL,
	`mime_type` text,
	`original_name` text,
	FOREIGN KEY (`car_id`) REFERENCES `cars`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX `car_images_car_id_idx` ON `car_images` (`car_id`);--> statement-breakpoint
CREATE TABLE `cars` (
	`id` text PRIMARY KEY NOT NULL,
	`brand` text NOT NULL,
	`model` text NOT NULL,
	`trim` text,
	`year` integer,
	`price_cents` integer NOT NULL,
	`listing_url` text,
	`odometer_km` integer,
	`fuel_type` text,
	`transmission` text,
	`gears` integer,
	`horsepower` integer,
	`torque_nm` integer,
	`cylinders` integer,
	`license_plate` text,
	`apk_valid_until` text,
	`seller_name` text,
	`seller_city` text,
	`seller_address` text,
	`trunk_width_mm` integer,
	`trunk_height_mm` integer,
	`trunk_liters_seats_up` integer,
	`trunk_liters_seats_folded` integer,
	`fuel_tank_liters` real,
	`blind_spot_monitor` integer,
	`parking_sensors_front` integer,
	`parking_sensors_rear` integer,
	`android_auto` integer,
	`apple_car_play` integer,
	`rearview_camera` integer,
	`radar_emergency_braking` integer,
	`upgraded_rims` integer,
	`adaptive_cruise` integer,
	`adaptive_cruise_stop_go` integer,
	`steering_aid` integer,
	`hill_hold` integer,
	`cruise_control` integer,
	`speed_limiter` integer,
	`folding_mirrors` integer,
	`highway_l_per_100km` real,
	`combined_l_per_100km` real,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL
);
